- name: download setup script
  get_url:
    dest: /tmp/setup_{{ node_js_version }}
    mode: u+x
    url: http://rpm.nodesource.com/setup_{{ node_js_version }}

- name: execute setup script
  shell: /tmp/setup_{{ node_js_version }}

- name: install dependencies
  yum:
    update_cache: yes
    name:
    - nodejs
    - build-essential
